-- AlterTable
ALTER TABLE `Palpite` MODIFY `metodoAposta` ENUM('LAY_0X1', 'LAY_0X2', 'LAY_0X3', 'LAY_GOLEADA', 'LAY_GOLEADACASA', 'LAY_GOLEADAVISITANTE', 'LAY_1X2', 'LAY_1X0', 'LAY_2X0', 'LAY_3X0', 'BACK_GOLEADA', 'BACK_CASA', 'BACK_VISITANTE', 'LAY_CASA', 'LAY_VISITANTE', 'OVER_0_5HT', 'OVER_1_5HT', 'OVER_2_5HT', 'OVER_3_5HT', 'OVER_0_5FT', 'OVER_1_5FT', 'OVER_2_5FT', 'OVER_3_5FT', 'OVER_4_5FT', 'OVER_5_5FT', 'OVER_6_5FT', 'OVER_7_5FT', 'UNDER_0_5FT', 'UNDER_1_5FT', 'UNDER_2_5FT', 'UNDER_3_5FT', 'UNDER_4_5FT', 'UNDER_5_5FT', 'UNDER_6_5FT', 'UNDER_7_5FT', 'UNDER_0_5HT', 'UNDER_1_5HT', 'UNDER_2_5HT', 'UNDER_3_5HT', 'UNDER_4_5HT', 'BACK_DUPLA_CHANCE', 'LAY_DUPLA_CHANCE') NULL;

-- CreateTable
CREATE TABLE `Sorteio` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `whatsapp` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `Sorteio_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
