-- CreateTable
CREATE TABLE `User` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `role` ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER',
    `subscriptionStatus` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'INACTIVE',
    `subscriptionExpiresAt` DATETIME(3) NULL,
    `criadoEm` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `User_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Palpite` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `esporte` VARCHAR(191) NOT NULL DEFAULT 'Futebol',
    `competicao` VARCHAR(191) NOT NULL,
    `jogo` VARCHAR(191) NOT NULL,
    `dataHora` DATETIME(3) NOT NULL,
    `palpite` VARCHAR(191) NOT NULL,
    `link` VARCHAR(191) NOT NULL,
    `criadoEm` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `oddpesquisada` DOUBLE NULL,
    `metodoAposta` ENUM('LAY_0X1', 'LAY_0X2', 'LAY_0X3', 'LAY_GOLEADA', 'LAY_1X0', 'LAY_2X0', 'LAY_3X0', 'BACK_GOLEADA', 'BACK_CASA', 'BACK_VISITANTE', 'LAY_CASA', 'LAY_VISITANTE', 'OVER_0_5HT', 'OVER_1_5HT', 'OVER_2_5HT', 'OVER_3_5HT', 'OVER_0_5FT', 'OVER_1_5FT', 'OVER_2_5FT', 'OVER_3_5FT', 'OVER_4_5FT', 'OVER_5_5FT', 'OVER_6_5FT', 'OVER_7_5FT', 'UNDER_0_5FT', 'UNDER_1_5FT', 'UNDER_2_5FT', 'UNDER_3_5FT', 'UNDER_4_5FT', 'UNDER_5_5FT', 'UNDER_6_5FT', 'UNDER_7_5FT', 'UNDER_0_5HT', 'UNDER_1_5HT', 'UNDER_2_5HT', 'UNDER_3_5HT', 'UNDER_4_5HT', 'BACK_DUPLA_CHANCE', 'LAY_DUPLA_CHANCE') NULL,
    `resultado` ENUM('PENDING', 'GREEN', 'RED') NOT NULL DEFAULT 'PENDING',
    `placar` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ApostaFeita` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `valorApostado` DOUBLE NOT NULL,
    `resultadoPNL` DOUBLE NULL,
    `data` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `usuarioId` INTEGER NOT NULL,
    `palpiteId` INTEGER NOT NULL,

    UNIQUE INDEX `ApostaFeita_usuarioId_palpiteId_key`(`usuarioId`, `palpiteId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
